zeebe:
  client:
    broker:
      gatewayAddress: "ZEEBE_GATEWAYHOST:443"
    security:
      plaintext: false
    cloud:
      client-id: "zeebe"
      client-secret: "ZEEBE_CLIENT_SECRET"
      auth-url: "https://KEYCLOAK_HOST:443/auth/realms/camunda-platform/protocol/openid-connect/token"
      audience: "zeebe-api"
