apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: camunda-greenfield
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 4
    volumeSize: 80
    privateNetworking: true

availabilityZones: ['us-east-1a', 'us-east-1b']