camunda:
  client:
    mode: saas
    client-id: jgqOS0s9niN61urDlp0_mOd24UT6Gs4U
    client-secret: aOu3CmBEhyVbOu5kQVi7InkHT-0..YRsp5Ijxg3KzRORthRAoWOCB3TXWO9yYHd4
    cluster-id: 5bc4132a-01e6-4ddb-92fa-426392f3f39f
    region: ont-1

spring:
  application:
    name: c8-high-perf-tasklist
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tasks_db;NON_KEYWORDS=VALUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

managment:
  metrics.tags.application: ${spring.application.name}
  endpoints.web.exposure.include: prometheus
