camunda:
  client:
    mode: selfmanaged
    zeebe:
      base-url: "https://my.domain.com"
      rest-address: "https://my.domain.com/rest"
      grpc-address: "https://my.domain.com"
    auth:
      client-id: "simpleinbound"
      client-secret: "xxx"
      issuer: "https://my.domain.com/auth/realms/camunda-platform/protocol/openid-connect/token"

operate:
  client:
    profile: oidc
    auth-url: "https://my.domain.com/auth/realms/camunda-platform/protocol/openid-connect/token"
    base-url: "https://my.domain.com/operate"
    client-id: "simpleinbound"
    client-secret: "xxx"
