camunda:
  client:
    mode: selfmanaged
    zeebe:
      rest-address: "${ZEEBE_REST_ADDRESS}"
      grpc-address: "https://dave01.gke.c8sm.com"
    auth:
      token-url: "${ZEEBE_AUTHORIZATION_SERVER_URL}"
      client-id: "${ZEEBE_CLIENT_ID}"
      client-secret: "${ZEEBE_CLIENT_SECRET}"