---
# Source: camunda-platform/templates/web-modeler/deployment-restapi.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-web-modeler-restapi
  labels:
    app: camunda-platform
    app.kubernetes.io/name: web-modeler
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: camunda-platform-9.3.2
    app.kubernetes.io/version: "8.4.3"
    app.kubernetes.io/component: restapi
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/name: web-modeler
      app.kubernetes.io/instance: camunda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: restapi
  template:
    metadata:
      labels:
        app: camunda-platform
        app.kubernetes.io/name: web-modeler
        app.kubernetes.io/instance: camunda
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: camunda-platform
        helm.sh/chart: camunda-platform-9.3.2
        app.kubernetes.io/version: "8.4.3"
        app.kubernetes.io/component: restapi
    spec:
      imagePullSecrets:
        - name: camunda-docker-registry
      initContainers:
        []
      containers:
        - name: web-modeler-restapi
          image: "registry.camunda.cloud/web-modeler-ee/modeler-restapi:8.4.3"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: JAVA_OPTIONS
              value: "-Xmx1536m"
            - name: CAMUNDA_IDENTITY_BASEURL
              value: "http://camunda-identity:80/identity"
            - name: CAMUNDA_IDENTITY_TYPE
              value: "KEYCLOAK"
            - name: CAMUNDA_MODELER_SECURITY_JWT_AUDIENCE_PUBLIC_API
              value: "web-modeler-public-api"
            - name: CAMUNDA_MODELER_SECURITY_JWT_AUDIENCE_INTERNAL_API
              value: "web-modeler-api"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://camunda-postgresql-web-modeler:5432/web-modeler"
            - name: SPRING_DATASOURCE_USERNAME
              value: "web-modeler"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: camunda-postgresql-web-modeler
                  key: password
            - name: RESTAPI_MAIL_HOST
              value: ""
            - name: RESTAPI_MAIL_PORT
              value: "587"
            - name: RESTAPI_MAIL_ENABLE_TLS
              value: "true"
            - name: RESTAPI_MAIL_FROM_ADDRESS
              value: "david.paroulek@camunda.com"
            - name: RESTAPI_MAIL_FROM_NAME
              value: "Camunda 8"
            - name: RESTAPI_SERVER_URL
              value: "https://dave01.aks.c8sm.com/modeler"
            - name: RESTAPI_PUSHER_HOST
              value: "camunda-web-modeler-websockets"
            - name: RESTAPI_PUSHER_PORT
              value: "80"
            - name: RESTAPI_PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: camunda-web-modeler
                  key: pusher-app-id
            - name: RESTAPI_PUSHER_KEY
              valueFrom:
                configMapKeyRef:
                  name: camunda-web-modeler
                  key: pusher-app-key
            - name: RESTAPI_PUSHER_SECRET
              valueFrom:
                secretKeyRef:
                  name: camunda-web-modeler
                  key: pusher-app-secret
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://dave01.aks.c8sm.com/auth/realms/camunda-platform"
            - name: RESTAPI_OAUTH2_TOKEN_ISSUER_BACKEND_URL
              value: "http://camunda-keycloak:80/auth/realms/camunda-platform"
            - name: ZEEBE_CLIENT_CONFIG_PATH
              value: /tmp/zeebe_client_cache.txt
            - name: JAVA_TOOL_OPTIONS
              value: "-Djavax.net.ssl.trustStore=/usr/local/certificates/keystore.jks -Djavax.net.ssl.trustStorePassword=changeit"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            - containerPort: 8091
              name: http-management
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http-management
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: keystore-volume
              readOnly: true
              mountPath: /usr/local/certificates
      volumes:
        - name: tmp
          emptyDir: {}
        - name: keystore-volume
          secret:
            secretName: custom-keystore
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
